---
title: "Untitled"
author: "Allie Cole and Scout Leonard"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
library(ggrepel)
```

```{r, echo = FALSE}
crab_data <- read_csv(here("data", "HTL-MAR-FiddlerCrabBodySize.csv"))
```

```{r, fig.alt = "A jitterplot of Crab Carapace lengths across latitudes shows greater widths at greater latitudes", echo = FALSE}
ggplot(data = crab_data, aes(x = Latitude, y = carapace_width)) +
  geom_jitter() +
  labs(title = "Crab Carapace Widths by Latitude",
       x = "Latitude",
       y = "Carapace Widths (mm)")
```


Crab carapace widths. 


```{r, echo = FALSE}
crab_subset <- crab_data %>% 
  group_by(Site) %>% 
  summarise(mean_width = round(mean(carapace_width), 2), 
            sd_width = round(sd(carapace_width), 2), 
            ss_width = n())


crab_table <- crab_subset %>% 
  kable(col.names = c("Site", "Mean Width", "Standard Devation Width", "Sample Size")) %>% 
  kable_classic()



crab_table
```

```{r, alt.text = "A scatterplot of mean annual water temperatures with mean crab carapace widths shows two clusters of points: one with lower water temperatures and larger carapace widths, and another with high water temperatures and lower carapace widths.", echo = FALSE}
crab_subset_2 <- crab_data %>% 
  group_by(Site) %>% 
  summarize(mean_carapace_width =(mean(carapace_width)),
            MATW = mean(MATW))

ggplot(data = crab_subset_2, aes(x = MATW, y = mean_carapace_width)) +
  geom_point(aes(color = Site), show.legend = FALSE) +
  geom_text_repel(aes(label = Site))
```

A scatterplot of mean annual water temperatures and mean carapace widths. 







